apiVersion: v1
kind: Service
metadata:
  name: email-service
spec:
  selector:
    app: email-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: grpc
      port: 9091
      targetPort: 9091
  type: ClusterIP 